[tool.poetry]
name = "python-backpack"
version = "1.1.4"
description = "A collection of personal scripts for json, File/Folder Operations, String Validation, Custom Errors, Cache and stuff."
authors = ["Maximiliano Rocamora"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
tox = "^4.0"
ruff = "^0.0.289"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
