name: Python Tests & Coverage

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --dev

    - name: Run Ruff
      if: ${{ matrix.python-version == '3.11' }}
      run: uv run ruff check .

    - name: Run Pyright
      if: ${{ matrix.python-version == '3.11' }}
      run: uv run pyright backpack tests

    - name: Run tests
      if: ${{ matrix.python-version != '3.11' }}
      run: uv run pytest

    - name: Run tests with branch coverage
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        uv run coverage run --branch --source=backpack -m pytest
        uv run coverage report -m --fail-under=99
        uv run coverage xml

    - name: Upload coverage.xml
      if: ${{ matrix.python-version == '3.11' }}
      uses: actions/upload-artifact@v7
      with:
        name: upload coverage
        path: ${{ github.workspace }}/coverage.xml
        if-no-files-found: warn

    # upload coverage.xml to codecov
    - name: Upload coverage.xml to codecov
      if: ${{ matrix.python-version == '3.11' }}
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}