name: Python Tox & Coverage

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Add path to PYTHONPATH
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions pipenv

    - name: Test with tox
      run: tox

    # copy coverage.xml from tox to path: '~/coverage.xml'
    - name: Upload coverage.xml
      if: ${{ matrix.python-version == '3.9' }}
      uses: actions/upload-artifact@v3
      with:
        name: upload tox-gh-actions-coverage
        path: ${{ github.workspace }}/coverage.xml
        if-no-files-found: warn

    # upload coverage.xml to codecov
    - name: Upload coverage.xml to codecov
      if: ${{ matrix.python-version == '3.9' }}
      uses: codecov/codecov-action@v3